### ISSUE TITLE
php82 doesn't allow dynamic property creation

### ISSUE THREAD

**Issue by yespire** [kevinoo/phpWhois#10]
@kevinoo 

Just notice an exception:

```
Runtime: PHP-8.2
Exception: Creation of dynamic property arin_handler::$deepWhois is deprecated
File: vendor/kevinoo/phpwhois/src/WhoisClient.php
Line: 492

```

Regards

**Comment by DavidAnderson684** [comment]
@kevinoo A PR that fixes this is available here: https://github.com/kevinoo/phpWhois/pull/11

**Comment by kevinoo** [comment]
Thanks @DavidAnderson684 :heart: 

Little note: I have to check if that attribute is actually used by some "Handler"  :muscle:
