### ISSUE TITLE
composer update unzip error

### ISSUE THREAD

**Issue by yespire** [kevinoo/phpWhois#4]
This is not a critical problem.

`composer update` command

1. on Linux (redhat/centos), works as expected
2. on Mac, yields the following error message when installing the package for the first time: 

 ```
Failed to extract kevinoo/phpwhois: (50) '/usr/bin/unzip' -qq '<PROJECT>/vendor/composer/tmp-7bba08f253d7ee13f07301f6286873fe.zip' -d '<PROJECT>/vendor/composer/a8016ac8'

error:  cannot create <PROJECT>/vendor/composer/a8016ac8/kevinoo-phpWhois-8ca26c5/tests/fixtures/?????.????.txt
        Illegal byte sequence
```

**Comment by kevinoo** [comment]
Hi @yespire 

on Mac, are you simply performing a `composer update` in your project? Try running `composer require kevinoo/phpwhois` :pray:

Let me know, 
Kevin

**Comment by yespire** [comment]
@kevinoo 

I'm getting the same error message when installing on mac:
1. composer require kevinoo/phpwhois
2. add  "kevinoo/phpwhois": "^6.3", to composer.json, then run "composer update"

**Comment by kevinoo** [comment]
I think the problem is this file `tests/fixtures/рег.рф.txt` :disappointed: 

if I should be create a dev-branch, can you test the version on MacOS for me?  :pray:

**Comment by yespire** [comment]
@kevinoo 

Of course, just ping me

**Comment by kevinoo** [comment]
Hi @yespire 
sorry for the late.

I created the "dev-4-composer-update-unzip-error" branch trying to correct the problem: could you use that branch as source when you can? :pray:  I also updated the repository on [Packagist (for Composer)](https://packagist.org/packages/kevinoo/phpwhois#dev-4-composer-update-unzip-error)

**Comment by yespire** [comment]
@kevinoo 

Just verified, the patch fixed the unzip issue
Thank you for the fix!

**Comment by kevinoo** [comment]
Thank you very much @yespire for your availability! 🙏🏻

As soon as I can, I will release the patch to the main branch 💪🏻
